name: 'dwh_transform'
version: '1.0.0'
config-version: 2

profile: 'dwh_transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_dw:
    staging:
      materialized: view
      schema: staging
    dimensions:
      materialized: table
      schema: dim
    facts:
      materialized: incremental
      schema: fact
    analytics:
      materialized: table
      schema: analytics